import type { ActiveFeature, PullRequestResult, Session, Turn } from "../types";
import { prMode } from "../utils/env";
import { summarizeChange } from "./llm";
import { getClientForChannel } from "./github";
import type { GithubClient } from "./github";
import { attachActiveFeature, endActiveFeature } from "./sessions";

/** Kinds of file operation `commitChange` can persist. */
export type CommitKind = "create" | "edit" | "delete";

/** Max length for a summary in the PR body. Prevents large files from bloating the body. */
const SUMMARY_MAX_LENGTH = 800;

/** Inputs describing one file operation that needs to be persisted. */
export interface CommitInput {
  kind: CommitKind;
  path: string;
  /** New file body for `create`/`edit`. For `delete`, the old contents (used in the PR body for context). */
  content: string;
  /** Original user-supplied prompt (for the PR body). */
  prompt: string;
  /** Existing blob SHA when editing on the default branch; omit for create. Required for delete (verified before commit). */
  sha?: string;
  /** When provided, overrides the auto-generated "Create X via Discord buddy" commit message. */
  commitMessage?: string;
}

/**
 * Outcome of a commit, for the caller to render in chat AND to feed into
 * `recordTurn`. Includes the change summary so handlers don't re-run
 * `summarizeChange`.
 */
export type CommitOutcome =
  | { mode: "direct"; summary: null }
  | {
      mode: "pr";
      pr: PullRequestResult;
      /** True if this commit attached to a session's existing feature PR. */
      attached: boolean;
      summary: string | null;
    };

/**
 * Persist a generated file. When `ONYX_PR_MODE` is on (default), opens a PR
 * (or attaches to the session's active feature PR if one is in flight);
 * otherwise commits straight to the default branch (legacy behavior).
 */
export async function commitChange(input: CommitInput, session: Session): Promise<CommitOutcome> {
  const client = getClientForChannel(session.channelId);

  if (!prMode()) {
    if (input.kind === "delete") {
      if (!input.sha) throw new Error("delete requires sha");
      await client.deleteFile(
        input.path,
        defaultCommitMessage(input),
        input.sha,
        (await client.getDefaultBranch()).name,
      );
    } else {
      await client.writeFile(input.path, input.content, defaultCommitMessage(input), input.sha);
    }
    return { mode: "direct", summary: null };
  }

  const reusable = await resolveReusableFeature(session, client);
  const summary =
    input.kind === "delete"
      ? null
      : await summarizeChange(input.kind, input.path, input.prompt, input.content);

  if (reusable) {
    return commitToExistingFeature(input, reusable, summary, client);
  }
  return openFreshFeature(input, session, summary, client);
}

/**
 * Build the cumulative PR body from every committed turn on this feature,
 * plus the about-to-be-recorded turn. Exported for tests.
 */
export function renderFeaturePullRequestBody(feature: ActiveFeature, pendingTurn: Turn): string {
  const turns = [...feature.turns, pendingTurn];
  const sections = turns
    .filter((t) => t.kind === "create" || t.kind === "edit" || t.kind === "delete")
    .map((t) => {
      const verb = t.kind === "create" ? "Created" : t.kind === "edit" ? "Edited" : "Deleted";
      const path = t.paths[0] ?? "(unknown path)";
      const lines = [`### ${verb} \`${path}\``, `**Prompt:** ${t.prompt}`];
      if (t.kind !== "delete") {
        let summaryBlock = (t.summary || "").trim() || "(summary unavailable)";
        if (summaryBlock.length > SUMMARY_MAX_LENGTH) {
          summaryBlock = summaryBlock.slice(0, SUMMARY_MAX_LENGTH).trimEnd() + "…";
        }
        lines.push("", summaryBlock);
      }
      return lines.join("\n");
    });
  return [
    "**Onyx feature PR — multiple commits batched into this branch.**",
    "",
    sections.join("\n\n"),
    "",
    "---",
    "🤖 generated by Onyx",
  ].join("\n");
}

interface ReusableFeature {
  branch: string;
  prNumber: number;
  prUrl: string;
  feature: ActiveFeature;
}

async function resolveReusableFeature(
  session: Session,
  client: GithubClient,
): Promise<ReusableFeature | null> {
  const f = session.active;
  if (!f || !f.branch || f.prNumber === null) return null;
  try {
    const pr = await client.getPullRequest(f.prNumber);
    if (pr.state !== "open" || pr.merged) {
      endActiveFeature(session);
      return null;
    }
    return {
      branch: f.branch,
      prNumber: f.prNumber,
      prUrl: pr.url,
      feature: f,
    };
  } catch {
    endActiveFeature(session);
    return null;
  }
}

async function commitToExistingFeature(
  input: CommitInput,
  reusable: ReusableFeature,
  summary: string | null,
  client: GithubClient,
): Promise<CommitOutcome> {
  const branchSha = await readBranchSha(input.path, reusable.branch, client);
  if ((input.kind === "edit" || input.kind === "delete") && branchSha === null) {
    throw new Error(`\`${input.path}\` does not exist on branch \`${reusable.branch}\`.`);
  }
  if (input.kind === "create" && branchSha !== null) {
    throw new Error(
      `\`${input.path}\` already exists on branch \`${reusable.branch}\`. Use /edit instead.`,
    );
  }
  if (input.kind === "delete") {
    await client.deleteFile(
      input.path,
      defaultCommitMessage(input),
      branchSha as string,
      reusable.branch,
    );
  } else {
    await client.writeFile(
      input.path,
      input.content,
      defaultCommitMessage(input),
      branchSha ?? undefined,
      reusable.branch,
    );
  }

  const pendingTurn: Turn = {
    kind: input.kind,
    paths: [input.path],
    prompt: input.prompt,
    summary,
    timestamp: Date.now(),
  };
  const body = renderFeaturePullRequestBody(reusable.feature, pendingTurn);
  await client.updatePullRequest(reusable.prNumber, body);

  return {
    mode: "pr",
    pr: {
      url: reusable.prUrl,
      number: reusable.prNumber,
      branch: reusable.branch,
    },
    attached: true,
    summary,
  };
}

async function openFreshFeature(
  input: CommitInput,
  session: Session,
  summary: string | null,
  client: GithubClient,
): Promise<CommitOutcome> {
  const base = await client.getDefaultBranch();
  const branch = client.buildBranchName(input.kind, input.path);
  await client.createBranch(branch, base.sha);
  if (input.kind === "delete") {
    if (!input.sha) {
      throw new Error("delete requires sha (resolved against default branch)");
    }
    await client.deleteFile(input.path, defaultCommitMessage(input), input.sha, branch);
  } else {
    await client.writeFile(
      input.path,
      input.content,
      defaultCommitMessage(input),
      input.sha,
      branch,
    );
  }

  const now = Date.now();
  const pendingTurn: Turn = {
    kind: input.kind,
    paths: [input.path],
    prompt: input.prompt,
    summary,
    timestamp: now,
  };
  const seedFeature: ActiveFeature = {
    branch,
    prNumber: null,
    title: `${input.kind}: ${input.path}`,
    paths: new Set<string>(),
    turns: [],
    createdAt: now,
  };
  const body = renderFeaturePullRequestBody(seedFeature, pendingTurn);
  const pr = await client.openPullRequest(seedFeature.title, body, branch, base.name);

  attachActiveFeature(session, {
    ...seedFeature,
    prNumber: pr.number,
  });

  return { mode: "pr", pr, attached: false, summary };
}

async function readBranchSha(
  path: string,
  branch: string,
  client: GithubClient,
): Promise<string | null> {
  const f = await client.readFile(path, branch);
  return f?.sha ?? null;
}

function defaultCommitMessage(input: CommitInput): string {
  if (input.commitMessage) return input.commitMessage;
  const verb = input.kind === "create" ? "Create" : input.kind === "edit" ? "Edit" : "Delete";
  return `${verb} ${input.path} via Discord buddy`;
}
