import { describe, expect, it } from "vitest";
import { renderFeaturePullRequestBody } from "../services/commitFlow";
import type { ActiveFeature, Turn } from "../types";

function feature(turns: Turn[] = []): ActiveFeature {
  return {
    branch: "onyx/create-x-1",
    prNumber: 7,
    title: "create: x.ts",
    paths: new Set<string>(),
    turns,
    createdAt: 0,
  };
}

function turn(overrides: Partial<Turn>): Turn {
  return {
    kind: "create",
    paths: ["x.ts"],
    prompt: "make x",
    summary: "- did a thing",
    timestamp: 0,
    ...overrides,
  };
}

describe("renderFeaturePullRequestBody()", () => {
  it("renders one section per committed turn plus the pending one", () => {
    const f = feature([turn({ kind: "create", paths: ["a.ts"], prompt: "first" })]);
    const body = renderFeaturePullRequestBody(
      f,
      turn({ kind: "edit", paths: ["a.ts"], prompt: "second" }),
    );
    expect(body).toContain("Created `a.ts`");
    expect(body).toContain("Edited `a.ts`");
    expect(body).toContain("**Prompt:** first");
    expect(body).toContain("**Prompt:** second");
    expect(body.indexOf("**Prompt:** first")).toBeLessThan(body.indexOf("**Prompt:** second"));
  });

  it("filters out non-write turns (ask / tool / feature / refine)", () => {
    const f = feature([
      turn({
        kind: "ask",
        paths: ["a.ts"],
        prompt: "what does it do?",
        summary: null,
      }),
    ]);
    const body = renderFeaturePullRequestBody(
      f,
      turn({ kind: "create", paths: ["b.ts"], prompt: "make b" }),
    );
    expect(body).not.toContain("what does it do?");
    expect(body).toContain("Created `b.ts`");
  });

  it("falls back to '(summary unavailable)' when a turn has no summary", () => {
    const f = feature();
    const body = renderFeaturePullRequestBody(f, turn({ kind: "create", summary: null }));
    expect(body).toContain("(summary unavailable)");
  });

  it("includes the Onyx footer", () => {
    const body = renderFeaturePullRequestBody(feature(), turn({}));
    expect(body).toContain("🤖 generated by Onyx");
  });

  it("truncates long summaries to prevent PR body bloat", () => {
    const longSummary =
      "- Did something\n" + "- Added support for CSS variables\n" + "x".repeat(1000);
    const f = feature();
    const body = renderFeaturePullRequestBody(f, turn({ summary: longSummary }));
    expect(body).toContain("…");
    expect(body).not.toContain(longSummary);
    const summaryInBody = body.split("### Created")[1]?.split("\n---")[0] ?? "";
    expect(summaryInBody.length).toBeLessThan(longSummary.length);
  });

  it("does not truncate summaries shorter than the limit", () => {
    const shortSummary = "- Fixed a bug";
    const f = feature();
    const body = renderFeaturePullRequestBody(f, turn({ summary: shortSummary }));
    expect(body).toContain(shortSummary);
    expect(body).not.toContain("…");
  });
});
